# Generated by Django 5.1 on 2024-09-02 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='users.order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_desc',
            field=models.TextField(max_length=100, verbose_name='Product Description'),
        ),
    ]
